version: '3.8'

services:

  # Nodejs App
  app-auth:
    container_name: app-auth
    build: .
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run start"
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_SEED: ${JWT_SEED}
      MAILER_ACTIVE: ${MAILER_ACTIVE}
      MAILER_SERVICE: ${MAILER_SERVICE}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_SECRET_KEY: ${MAILER_SECRET_KEY}
      WEBSERVICE_URL: ${WEBSERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo-db

  # MongoDB Service
  mongo-db:
    image: mongo:6.0.6
    restart: always
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"

  # PostgreSQL Service (Opcional - Comentar si no se usa)
  # postgres-db:
  #   image: postgres:15.3
  #   restart: always
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: my-db
  #     POSTGRES_PASSWORD: 123456
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"